### Introduction to Machine Learning
##### https://keras.io/getting-started/sequential-model-guide/
#### prepared by Chao-Lin Liu
###### 目前這一個程式的辨識率很差
###### 改變一下你的 sequential model 的設定，看看能不能達成比較高的辨識率？
###### 能不能把辨識率提高到 90% 以上？

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("introML2019.taskx.train.csv")

In [2]:
df[0:5]

feature_0  feature_1  feature_2  feature_3  feature_4  feature_5  \
0    3.03072    3.82764    0.58316    0.05098    2.33048    1.31349   
1    2.06554    2.58245    2.78158    2.64259    0.36718    0.72675   
2    4.79113    4.26817    3.31938    1.69178    0.60181    0.97848   
3    0.54282    0.70391    4.64737    2.79710    1.97160    0.72203   
4    3.03771    2.79512    1.23405    0.43138    0.71433    0.77471   

   feature_6  feature_7  feature_8  feature_9  feature_10  feature_11  \
0    0.83424    3.03314    0.94328    1.23016     0.24975     0.85205   
1    5.03764    2.74495    0.23774    0.50992     0.52516     0.08850   
2    2.77091    0.64957    0.15596    0.81251     0.47414     1.27370   
3    4.49158    0.01500    0.91521    0.93423     0.31449     0.01357   
4    3.04295    1.22548    3.13544    0.38265     0.33434     1.14438   

   feature_12  feature_13  label  
0     0.34522     1.33981      0  
1     0.16748     1.71180      0  
2     1.66604     1.27203      0  
3     0.78556     1.27886      0  
4     0.99043     1.28083      0

In [3]:
X_train = np.array(df.iloc[:,0:14])
y_train = np.array(df.iloc[:,14:15]).reshape(-1)

In [4]:
#shuffle data
from sklearn.utils import shuffle
X_train, y_train = shuffle(X_train, y_train, random_state=119)

In [5]:
# 以下的步驟在 Introduction to Machine learning 課程並沒有講到
# 我們把 y 的數值變成了向量 － one-hot vector
#
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils
# encode class values as integers
encoder = LabelEncoder()
encoder.fit(y_train)
encoded_npy = encoder.transform(y_train)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_npy = np_utils.to_categorical(encoded_npy)

Using TensorFlow backend.


In [196]:
# 你可以試著增加 Dense 層的數目、或者改變個別 Dense 層的 nodes 數目、或者改變 activation functions
#
from keras.models import Sequential
from keras.layers import Dense, Dropout
# define baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(9, input_dim=14, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(100, activation='relu'))
    model.add(Dense(512, activation='relu'))
    model.add(Dense(5, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [197]:
model2 = baseline_model()

In [198]:
# 在這裡，你可以嘗試增減 epochs 和 batch_size
model2.fit(X_train , dummy_npy, epochs=250, batch_size=1000, verbose=1, shuffle=True)

Epoch 1/250
50000/50000 [==============================] - 1s 23us/step - loss: 1.3526 - acc: 0.4194
Epoch 2/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.9972 - acc: 0.5965
Epoch 3/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.7075 - acc: 0.7199
Epoch 4/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.5461 - acc: 0.7853
Epoch 5/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.4654 - acc: 0.8179
Epoch 6/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.4064 - acc: 0.8411
Epoch 7/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.3721 - acc: 0.8554
Epoch 8/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.3328 - acc: 0.8719
Epoch 9/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.3060 - acc: 0.8851
Epoch 10/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.2885 - acc: 0.893

50000/50000 [==============================] - 0s 4us/step - loss: 0.0508 - acc: 0.9837
Epoch 163/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.0513 - acc: 0.9835
Epoch 164/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.0535 - acc: 0.9828
Epoch 165/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.0511 - acc: 0.9831
Epoch 166/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.0531 - acc: 0.9829
Epoch 167/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.0535 - acc: 0.9822
Epoch 168/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.0483 - acc: 0.9844
Epoch 169/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.0509 - acc: 0.9833
Epoch 170/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.0512 - acc: 0.9833
Epoch 171/250
50000/50000 [==============================] - 0s 4us/step - loss: 0.0542 - acc: 0

In [199]:
df2 = pd.read_csv("introML2019.taskx.test.csv")

In [200]:
testX = np.array(df2.iloc[:,0:14])

In [201]:
predicty = model2.predict(testX)

In [202]:
predicty[0:5]

array([[2.1589108e-01, 1.6356025e-29, 7.8410888e-01, 3.5834715e-14,
        5.6188176e-25],
       [1.0000000e+00, 0.0000000e+00, 0.0000000e+00, 0.0000000e+00,
        0.0000000e+00],
       [1.0000000e+00, 7.6424217e-37, 5.1492806e-26, 3.0116218e-21,
        9.8191396e-35],
       [4.4315794e-01, 0.0000000e+00, 5.5684209e-01, 3.7936011e-29,
        3.9469377e-27],
       [1.0000000e+00, 0.0000000e+00, 6.7197081e-11, 2.6682022e-27,
        1.1980571e-32]], dtype=float32)

In [203]:
testy = np.array(df2.iloc[:,14:15]).reshape(-1)

In [204]:
predicty = encoder.inverse_transform([np.argmax(item) for item in predicty])

In [205]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(testy,predicty))

[[2355    0   42    7   96]
 [   0 2496    2    2    0]
 [   8    3 2456   16   17]
 [   0   11   22 2467    0]
 [  12    1   12    6 2469]]


In [206]:
print(classification_report(testy,predicty))

              precision    recall  f1-score   support

           0       0.99      0.94      0.97      2500
           1       0.99      1.00      1.00      2500
           2       0.97      0.98      0.98      2500
           3       0.99      0.99      0.99      2500
           4       0.96      0.99      0.97      2500

    accuracy                           0.98     12500
   macro avg       0.98      0.98      0.98     12500
weighted avg       0.98      0.98      0.98     12500

